### ISSUE TITLE
执行命令后返回的日志不完整

### ISSUE THREAD

**Issue by haoye12138** [zkhssb/NectarRCON#12]
作者大大，为什么帕鲁执行命令返回的都是不完整的，比如返回的服务器名称只有前部分，返回的steamid也只有部分数字，后面的都没有了，游戏里执行命令是可以显示完全的

**Comment by zkhssb** [comment]
过几天为这个游戏单独写一个协议支持

**Comment by huangxiuqi** [comment]
抓包看了下，当有中文内容时，连RCON协议的格式都不正确了，长度字段114个字节，但整个数据包才104个字节，而且返回的数据就是不全的，没得救。PacketID也没有实现，可能不看重RCON这个功能吧，游戏内应该是他们自己的协议，支持的肯定更好。

**Comment by haoye12138** [comment]
日志里有个情况是，存在两名玩家的时候，返回的第一名玩家的信息是完整的，但第二名玩家信息缺失更为严重。

**Comment by zkhssb** [comment]
先关闭了哈，这个是幻兽的问题
