### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by MBTYthe** [zkhssb/NectarRCON#14]
Sorry if I'm asking the question in the wrong place, but I don't really understand how to use Github. I kindly ask you to make a version for working on the command line. Or add the ability to execute commands in the current version via the console

**Comment by zkhssb** [comment]
Hi MBTYthe, NectarRcon has no plans to support CLI, If you use the command line, you can try [go-rcon-cli](https://github.com/gorcon/rcon-cli)
