### ISSUE TITLE
【新功能建议】 上键使用历史执行过的命令

### ISSUE THREAD

**Issue by mcitem** [zkhssb/NectarRCON#16]
希望在输入窗口中按上键可以“自动输入”历史执行过的命令，然后可以修改或是直接执行；

这个表述可能不太清楚，例如windows的powershell执行过命令以后，只要按方向键上键就能快速地再执行一次这个命令
；这与linux的bash环境下执行命令类似，同样可以自动获取历史执行的命令

**Comment by zkhssb** [comment]
哎嘿,其实已经有了 只是我还没有发布 https://github.com/zkhssb/NectarRCON/commit/e7349a9bd8533522b7c105fe3e0ab79325ad8e05

**Comment by mcitem** [comment]
我不会编译<>，action好像也找不到可以直接下载的东西😂

**Comment by zkhssb** [comment]
稍等 我给你编译一份吧

**Comment by zkhssb** [comment]
好了 https://s.yingen.top/EasyBot/App/NectarRCON.exe

**Comment by zkhssb** [comment]
ok了 [点我下载](https://s.yingen.top/EasyBot/App/NectarRCON.exe)

**Comment by mcitem** [comment]
谢谢 生效了已经 可以正常获取历史命令
