### ISSUE TITLE
连接自动断开后在连接会报多个认证成功

### ISSUE THREAD

**Issue by huajihuaji233** [zkhssb/NectarRCON#6]
没有设置自动重播嘛，还有输入中文服务器返回是乱码的，这是服务端问题嘛，发送到服务器和接受到消息的是哪条方法

**Comment by zkhssb** [comment]
是Group连接还是单个连接遇到的问题？
所有消息都是UTF8编码传输,如果不是这个编码那就会乱码
发送到服务器和接收是用的 [NectarRCON.Adapter.Minecraft](https://github.com/zkhssb/NectarRCON/blob/master/NectarRCON.Adapter.Minecraft/MinecraftRconClient.cs) <-> UI [Multi/Single Connection](https://github.com/zkhssb/NectarRCON/tree/master/NectarRCON/Rcon)

**Comment by zkhssb** [comment]
在看了

**Comment by zkhssb** [comment]
这个问题应该已经解决了,如果没其他问题的话可以关闭这个Issue了
